name: Task
description: Specific, decomposable, and estimable development tasks.
type: "Task"
body:
  - type: markdown
    id: title
    attributes:
      value: "Suggested Format: [Module] Verb + Core Objective"

  - type: textarea
    id: description
    attributes:
      label: Objective
      description: Briefly describe what this issue will achieve once completed.
      placeholder: |
        Implement basic account system: registration, login, and fetching current user info.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: A checklist to verify the task is complete.
      placeholder: Use - [ ] to list verifiable points.
