// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { existsSync } from "node:fs";
import { defineConfig, env } from "prisma/config";

// Bun 1.4 no longer forwards the variables it loads from `.env` files to the
// `prisma` process spawned by `bunx`, so load the right file here. Bun keeps
// the ambient environment, so an explicitly exported value still wins.
const envFile = process.env.NODE_ENV === "test" ? ".env.test" : ".env";

if (existsSync(envFile)) {
	process.loadEnvFile(envFile);
}

export default defineConfig({
	schema: "prisma/",
	migrations: {
		path: "prisma/migrations",
	},
	datasource: {
		url: env("DATABASE_URL"),
	},
});
